import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

import { Providers } from "@/app/providers";

import Navbar from "@/components/navbar";

export const metadata = {
  title: "Animux",
  description: "Generated by create next app",
  favicon: "/favicon.ico",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning className="scroll-smooth">
      <body
        className={
          montserrat.className +
          " max-w-[100%] overflow-x-hidden" +
          " bg-background font-sans" +
          " antialiased"
        }
      >
        <Providers>
          <Navbar></Navbar>
          {children}
        </Providers>
      </body>
    </html>
  );
}
